linters:
  enable-all: true
  disable:
    - exportloopref # Deprecated
    - exhaustruct # Noisy
    - tagliatelle # Triggers on JSON struct tags we don't control (NPM or PyPI specific)
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com
